Repository brevia-ai/brevia, pull requests merged in 2023-10, with the labels that each got.

#1 Add PyPI support with publish workflow
  .github/workflows/publish.yml
  .gitignore
  pyproject.toml
Labels: release:patch

#2 Fix project metadata
  LICENSE
  README.md
  docker-compose.yml
  pyproject.toml
Labels: release:patch

#3 Fix db migration commands
  brevia/alembic/__init__.py
  brevia/commands.py
Labels: release:patch

#4 Fix publish package workflow
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: release:patch

#5 Badges in README.md
  README.md
Labels: documentation

#8 Handle Q/A defaults in collection metadata
  .env.sample
  brevia/language.py
  brevia/prompts/qa/default.system.yaml
  brevia/query.py
  brevia/routers/qa_router.py
  pyproject.toml
Labels: enhancement

#12 refactor: prompt endpoint into chat
  .github/workflows/cs.yml
  brevia/postman/Brevia API.postman_collection.json
  brevia/routers/qa_router.py
Labels: release:patch

#10 Introduce LLM related unit tests
  .env.sample
  README.md
  brevia/chat_history.py
  brevia/index.py
  brevia/models.py
  brevia/postman/Brevia API.postman_collection.json
  brevia/query.py
  brevia/routers/analyze_router.py
  brevia/routers/audio_router.py
  brevia/routers/index_router.py
  brevia/routers/qa_router.py
  tests/.env.sample
  tests/conftest.py
  tests/files/empty.pdf
  tests/files/silence.mp3
  tests/routers/test_analyze_router.py
  tests/routers/test_app_routes.py
  tests/routers/test_audio_router.py
  tests/routers/test_collections_router.py
  tests/routers/test_index_router.py
  tests/routers/test_qa_router.py
  tests/test_index.py
  tests/test_models.py
  tests/test_query.py
Labels: enhancement
