Repository brevia-ai/brevia, pull requests merged in 2024-10, with the labels that each got.

#70 Env vars and docker files review
  .env.sample
  .github/workflows/release.yml
  Dockerfile
  brevia/settings.py
  docker-compose.yml
Labels: release:patch

#71 Set default value for BREVIA_ENV_SECRETS in docker compose
  docker-compose.yml
Labels: bug, release:patch

#75 Refactor: use `init_splitting_data` with cache annotation
  brevia/index.py
  brevia/routers/app_routers.py
  tests/conftest.py
Labels: release:patch

#76 Handle configuration in db with new endpoints
  brevia/alembic/versions/24b025d48e0a_config_table.py
  brevia/connection.py
  brevia/models.py
  brevia/postman/Brevia API.postman_collection.json
  brevia/routers/app_routers.py
  brevia/routers/config_router.py
  brevia/settings.py
  docs/assets/brevia-schema.png
  docs/config.md
  docs/database.md
  docs/endpoints_overview.md
  tests/.env.sample
  tests/conftest.py
  tests/routers/test_config_router.py
  tests/test_settings.py
Labels: release:minor
