Repository brevia-ai/brevia, pull requests merged in 2024-01, with the labels that each got.

#32 Upgrade langchain - new metadata filter operators
  brevia/async_jobs.py
  brevia/chat_history.py
  brevia/collections.py
  brevia/connection.py
  brevia/dependencies.py
  brevia/index.py
  brevia/query.py
  brevia/routers/index_router.py
  poetry.lock
  pyproject.toml
  tests/test_query.py
Labels: release:patch

#31 Initial documentation site using Mkdocs
  .env.sample
  .github/workflows/docs.yml
  .gitignore
  README.md
  brevia/commands.py
  brevia/routers/analyze_router.py
  brevia/routers/audio_router.py
  brevia/routers/chat_history_router.py
  brevia/routers/collections_router.py
  brevia/routers/index_router.py
  brevia/routers/jobs_router.py
  brevia/routers/qa_router.py
  brevia/routers/status_router.py
  brevia/settings.py
  brevia/utilities/openapi.py
  docs/chat_search.md
  docs/config.md
  docs/database.md
  docs/document_index.md
  docs/endpoints/chat_and_history.md
  docs/endpoints/collections.md
  docs/endpoints/documents_index.md
  docs/endpoints/status.md
  docs/endpoints/summarize_analyze.md
  docs/endpoints/transcribe.md
  docs/index.md
  docs/models/cohere.md
  docs/models/openai.md
  docs/models/other_models.md
  docs/security.md
  docs/services.md
  docs/setup.md
  main.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
  tests/test_commands.py
  tests/utilities/test_openapi.py
Labels: documentation

#34 Update document index metadata endpoint
  brevia/index.py
  brevia/routers/index_router.py
  tests/routers/test_index_router.py
Labels: release:patch

#36 Fix token usage callback error
  brevia/callback.py
  brevia/routers/qa_router.py
Labels: release:patch

#37 New /completion endpoint
  brevia/completions.py
  brevia/postman/Brevia API.postman_collection.json
  brevia/routers/app_routers.py
  brevia/routers/completion_router.py
  tests/routers/test_completion_router.py
  tests/test_completions.py
Labels: release:patch

#38 Chat response user evaluation endpoint - `/evaluate`
  brevia/alembic/versions/b34017752e45_chat_history_evaluation.py
  brevia/chat_history.py
  brevia/postman/Brevia API.postman_collection.json
  brevia/postman/Brevia API.postman_environment.json
  brevia/routers/chat_history_router.py
  brevia/routers/collections_router.py
  tests/routers/test_chat_history_router.py
Labels: release:patch

#39 Fix `qa_completion_llm` configuration usage in `/completions` endpoint
  brevia/completions.py
Labels: release:patch

#40 Use end of day and start of day in history filter
  brevia/chat_history.py
  tests/test_chat_history.py
Labels: bug, release:patch
